# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer2.codocs.com:
  orderer3.codocs.com:
  orderer4.codocs.com:
  orderer5.codocs.com:

networks:
  network:

services:

  orderer2.codocs.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=8050
    container_name: orderer2.codocs.com
    networks:
      - network
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/codocs.com/orderers/orderer2.codocs.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/codocs.com/orderers/orderer2.codocs.com/tls/:/var/hyperledger/orderer/tls
      - orderer2.codocs.com:/var/hyperledger/production/orderer
    ports:
      - 8050:8050

  orderer3.codocs.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=9050
    container_name: orderer3.codocs.com
    networks:
      - network
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/codocs.com/orderers/orderer3.codocs.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/codocs.com/orderers/orderer3.codocs.com/tls/:/var/hyperledger/orderer/tls
      - orderer3.codocs.com:/var/hyperledger/production/orderer
    ports:
      - 9050:9050

  orderer4.codocs.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=10050
    container_name: orderer4.codocs.com
    networks:
      - network
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/codocs.com/orderers/orderer4.codocs.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/codocs.com/orderers/orderer4.codocs.com/tls/:/var/hyperledger/orderer/tls
      - orderer4.codocs.com:/var/hyperledger/production/orderer
    ports:
      - 10050:10050

  orderer5.codocs.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=11050
    container_name: orderer5.codocs.com
    networks:
      - network
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/codocs.com/orderers/orderer5.codocs.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/codocs.com/orderers/orderer5.codocs.com/tls/:/var/hyperledger/orderer/tls
      - orderer5.codocs.com:/var/hyperledger/production/orderer
    ports:
      - 11050:11050
