version: '2'

volumes:
  orderer.codocs.com:
  peer0.patient.codocs.com:
  peer1.patient.codocs.com:
  peer0.provider.codocs.com:
  peer1.provider.codocs.com:
  peer0.admin.codocs.com:
  peer1.admin.codocs.com:
  
networks:
  network:

services:

  orderer.codocs.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.codocs.com
    container_name: orderer.codocs.com
    networks:
      - network

  peer0.patient.codocs.com:
    container_name: peer0.patient.codocs.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.patient.codocs.com
    networks:
      - network

  peer1.patient.codocs.com:
    container_name: peer1.patient.codocs.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.patient.codocs.com
    networks:
      - network

  peer0.provider.codocs.com:
    container_name: peer0.provider.codocs.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.provider.codocs.com
    networks:
      - network

  peer1.provider.codocs.com:
    container_name: peer1.provider.codocs.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.provider.codocs.com
    networks:
      - network
    
  peer0.admin.codocs.com:
    container_name: peer0.admin.codocs.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.admin.codocs.com
    networks:
      - network

  peer1.admin.codocs.com:
    container_name: peer1.admin.codocs.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.admin.codocs.com
    networks:
      - network  

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.patient.codocs.com:7051
      - CORE_PEER_LOCALMSPID=patientMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/patient.codocs.com/peers/peer0.patient.codocs.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/patient.codocs.com/peers/peer0.patient.codocs.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/patient.codocs.com/peers/peer0.patient.codocs.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/patient.codocs.com/users/Admin@patient.codocs.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.codocs.com
      - peer0.patient.codocs.com
      - peer1.patient.codocs.com
      - peer0.provider.codocs.com
      - peer1.provider.codocs.com
      - peer0.admin.codocs.com
      - peer1.admin.codocs.com
    networks:
      - network
