# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.codocs.com:
    container_name: orderer.codocs.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/codocs.com/orderers/orderer.codocs.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/codocs.com/orderers/orderer.codocs.com/tls/:/var/hyperledger/orderer/tls
        - orderer.codocs.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.patient.codocs.com:
    container_name: peer0.patient.codocs.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.patient.codocs.com
      - CORE_PEER_ADDRESS=peer0.patient.codocs.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.patient.codocs.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.patient.codocs.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.patient.codocs.com:7051
      - CORE_PEER_LOCALMSPID=patientMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/patient.codocs.com/peers/peer0.patient.codocs.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/patient.codocs.com/peers/peer0.patient.codocs.com/tls:/etc/hyperledger/fabric/tls
        - peer0.patient.codocs.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.patient.codocs.com:
    container_name: peer1.patient.codocs.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.patient.codocs.com
      - CORE_PEER_ADDRESS=peer1.patient.codocs.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.patient.codocs.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.patient.codocs.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.patient.codocs.com:7051
      - CORE_PEER_LOCALMSPID=patientMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/patient.codocs.com/peers/peer1.patient.codocs.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/patient.codocs.com/peers/peer1.patient.codocs.com/tls:/etc/hyperledger/fabric/tls
        - peer1.patient.codocs.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.provider.codocs.com:
    container_name: peer0.provider.codocs.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.provider.codocs.com
      - CORE_PEER_ADDRESS=peer0.provider.codocs.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.provider.codocs.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.provider.codocs.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.provider.codocs.com:10051
      - CORE_PEER_LOCALMSPID=providerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/provider.codocs.com/peers/peer0.provider.codocs.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/provider.codocs.com/peers/peer0.provider.codocs.com/tls:/etc/hyperledger/fabric/tls
        - peer0.provider.codocs.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.provider.codocs.com:
    container_name: peer1.provider.codocs.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.provider.codocs.com
      - CORE_PEER_ADDRESS=peer1.provider.codocs.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.provider.codocs.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.provider.codocs.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.provider.codocs.com:9051
      - CORE_PEER_LOCALMSPID=providerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/provider.codocs.com/peers/peer1.provider.codocs.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/provider.codocs.com/peers/peer1.provider.codocs.com/tls:/etc/hyperledger/fabric/tls
        - peer1.provider.codocs.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.admin.codocs.com:
    container_name: peer0.admin.codocs.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.admin.codocs.com
      - CORE_PEER_ADDRESS=peer0.admin.codocs.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.admin.codocs.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.admin.codocs.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.admin.codocs.com:12051
      - CORE_PEER_LOCALMSPID=adminMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/admin.codocs.com/peers/peer0.admin.codocs.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/admin.codocs.com/peers/peer0.admin.codocs.com/tls:/etc/hyperledger/fabric/tls
        - peer0.admin.codocs.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.admin.codocs.com:
    container_name: peer1.admin.codocs.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.admin.codocs.com
      - CORE_PEER_ADDRESS=peer1.admin.codocs.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.admin.codocs.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.admin.codocs.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.admin.codocs.com:11051
      - CORE_PEER_LOCALMSPID=adminMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/admin.codocs.com/peers/peer1.admin.codocs.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/admin.codocs.com/peers/peer1.admin.codocs.com/tls:/etc/hyperledger/fabric/tls
        - peer1.admin.codocs.com:/var/hyperledger/production
    ports:
      - 12051:12051
